name: Checkout Repository

on: [push]

jobs:
  checkout-repository:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: Display repository files
        run: ls -la