name: Hello World Pipeline

on: [push]

jobs:
  hello-world-pipeline:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print tasks
        run: echo "Starting Pipeling"
        run: echo "Pipeline complete"