name: Lab 12 Branch Specific Pipeline
on:
  push:
    branches: [main]

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
          - name: checkout Code
            uses: actions/checkout@v4

          - name: Display message
            run: echo "Allowed to deploy only on main Branches"