name: Lab 10 Build Artifact

on: [push]

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Build Artifact
        run: echo "Build Successful" > build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.txt