name: Lab 7 Environment Variables

on: [push, pull_request]

env:
  APP_NAME: my-web-app
  ENVIRONMENT: dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Install Dependencies
        run: echo "npm Installing dependencies..."

      - name: Run tests
        run: echo "npm Running tests....." 

      - name: Display Environment Variables
        run: |
          echo "Application Name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"


    
