name: Lab 8 Multiple Jobs

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: Run Test
        run: echo "Running Tests"
    
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out code
        uses: actions/checkout@v4

      - name: Build Application
        run: echo "Building Application"
