name: NodeJS CI Pipeline

on: [push]

jobs:
  NodeJS-CI:
    runs-on: ubuntu-latest

    steps:

      - name: Set Up NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: "20"

      - name: Install Dependencies
        run: echo "npm Installing dependencies..." 

      - name: Run Tests
        run: echo "npm Running tests....."

      - name: Build Application
        run: echo "npm Building application..."