name: Node.js CI

on: [push]

jobs:
  test-javascript:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Pull your code from your repo onto the cloud computer
      - name: Copy Repo Code
        uses: actions/checkout@v4

      # Step 2: Install the language environment
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Run your regular project commands
      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: npm test