name: Pull Request Validation

on: [push]

env:
  CHECK: Validating

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: Validation
        run: echo "$CHECK Pull Request"