name: Secure Secret Handling

on: [push]

jobs:
  run-api-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Secrets Securely
        env:
          API_TOKEN: ${{secrets.API_TOKEN}}
        run: |
          echo "Using API TOKEN securely in the workflow"
          echo "API TOKEN: $API_TOKEN"
